# Generated by Django 6.0.4 on 2026-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentprofile_face_encoding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
