# Generated by Django 6.0.4 on 2026-06-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_teacher_subjects_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='BCA', max_length=200),
        ),
    ]
