# Generated by Django 6.0.4 on 2026-06-11 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_teacherattendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_activity_time', models.TimeField(auto_now_add=True)),
                ('classes_taught', models.IntegerField(default=1)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.teacher')),
            ],
            options={
                'ordering': ['-date', '-first_activity_time'],
                'unique_together': {('teacher', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='TeacherAttendanceRecord',
        ),
    ]
