# Generated by Django 6.0.4 on 2026-06-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_teacherattendance_delete_teacherattendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='face_encoding',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_faces/'),
        ),
    ]
